steps:
- name: 'ubuntu'
  args: ['bash', 'build-npmrc.bash', '${_NPM_TOKEN}']
# Set build server to true
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'config'
  - 'set'
  - 'build_server:true'
# Install eslint
# - name: 'gcr.io/cloud-builders/npm'
#   args:
#   - 'install'
#   - 'eslint@3.19.0'
# Install the product
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'install'
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'dedupe'
#List the installed packages
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'list'
#run the tests
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'install'
  - 'mocha'
  - 'g'
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'test'
#remove the dev dependencies
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'prune'
  - '--production'
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'dedupe'
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'list'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/${PROJECT_ID}$_PROJECT_ID/${BRANCH_NAME}$_BRANCH_NAME/${REPO_NAME}$_REPO_NAME:latest'
  - '-t'
  - 'gcr.io/${PROJECT_ID}$_PROJECT_ID/${BRANCH_NAME}$_BRANCH_NAME/${REPO_NAME}$_REPO_NAME:$_VERSION.$SHORT_SHA'
  - '-f'
  - 'Dockerfile'
  - '.'

images:
- 'gcr.io/${PROJECT_ID}$_PROJECT_ID/${BRANCH_NAME}$_BRANCH_NAME/${REPO_NAME}$_REPO_NAME:latest'
- 'gcr.io/${PROJECT_ID}$_PROJECT_ID/${BRANCH_NAME}$_BRANCH_NAME/${REPO_NAME}$_REPO_NAME:$_VERSION.$SHORT_SHA'

substitutions:
  _VERSION: v1
  _BRANCH_NAME: 
  _REPO_NAME:
  _PROJECT_ID:
  _NPM_TOKEN:
  